#!/bin/bash

curl -X POST "http://localhost:29193/management/v2/catalog/request" \
  -H 'Content-Type: application/json' \
  -d '{  "@context": {    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"  },  "counterPartyAddress": "http://provider:19194/protocol",  "protocol": "dataspace-protocol-http"}' \
-s | jq '."dcat:dataset"."odrl:hasPolicy"."@id"' | tr -d \"
