#!/bin/bash
finalizado=false

Scripts/crearArtefacto

artefacto=$(Scripts/obtenerCatalogo)
echo "ID del artefacto a negociar: $artefacto"

contrato=$(Scripts/negociarContrato $artefacto)
echo "ID del contrato: $contrato"
while ! $finalizado; do 
  estado=$(Scripts/comprobarEstado $contrato "estado")
  if [ $estado = "FINALIZED" ]; then 
    finalizado=true
  fi
done
contratoExitoso=$(Scripts/comprobarEstado $contrato "id")

echo "El contract agreement id: $contratoExitoso"

# Aquí puedo poner el pull o el push, según necesite
# Scripts/transferenciaPush $contratoExitoso
# Scripts/transferenciaPull $contratoExitoso
