#!/bin/bash

if [ $2 = "estado" ]; then
  curl -X GET "https://sergio.arlabdevelopments.com:29193/management/v2/contractnegotiations/$1" \
    --header 'x-api-key: password' \
    --header 'Content-Type: application/json' \
  -s  | jq '.state' |  tr -d \" 
else
    curl -X GET "https://sergio.arlabdevelopments.com:29193/management/v2/contractnegotiations/f5c54daa-6a22-4458-9e83-4642832dc822" \
    --header 'x-api-key: password' \
    --header 'Content-Type: application/json' \
  -s  | jq '.contractAgreementId' |  tr -d \" 
fi