#!/bin/bash

curl -X POST "https://<url>:29193/management/v2/transferprocesses" \
  --header 'x-api-key: password' \
  -H "Content-Type: application/json" \
  -d "{
    \"@context\": {
      \"@vocab\": \"https://w3id.org/edc/v0.0.1/ns/\"
    },
    \"@type\": \"TransferRequestDto\",
    \"connectorId\": \"provider\",
    \"counterPartyAddress\": \"https://<url>:19194/protocol\",
    \"contractId\": \"$1\",
    \"assetId\": \"assetId\",
    \"protocol\": \"dataspace-protocol-http\",
    \"transferType\":\"HttpData-PULL\",
    \"dataDestination\": {
      \"type\": \"HttpProxy\"
    }
  }" \
  -s | jq


