#!/bin/bash

curl -X POST "https://<url>:29193/management/v2/transferprocesses" \
  --header 'x-api-key: password' \
  -H "Content-Type: application/json" \
  -d "{
    \"@context\": {
      \"@vocab\": \"https://w3id.org/edc/v0.0.1/ns/\"
    },
    \"@type\": \"TransferRequestDto\",
    \"connectorId\": \"provider\",
    \"counterPartyAddress\": \"https://<url>:19194/protocol\",
    \"contractId\": \"$1\",
    \"assetId\": \"assetId\",
    \"protocol\": \"dataspace-protocol-http\",
    \"transferType\":\"HttpData-PULL\",
    \"dataDestination\": {
      \"type\": \"HttpProxy\"
    }
  }" \
  -s | jq


hi all, I am trying to transfer data between two connectors in version 0.7.0, but I get the error: ``java.lang.NullPointerException: Cannot invoke "org.eclipse.edc.spi.types.domain.DataAddress.getType()" because "this.dataDestination" is null`` when I run this curl: 
```curl -X POST "https://<url>:29193/management/v2/transferprocesses" \
  --header 'x-api-key: password' \
  -H "Content-Type: application/json" \
  -d "{
    \"@context\": {
      \"@vocab\": \"https://w3id.org/edc/v0.0.1/ns/\"
    },
    \"@type\": \"TransferRequestDto\",
    \"connectorId\": \"provider\",
    \"counterPartyAddress\": \"https://<url>:19194/protocol\",
    \"contractId\": \"$1\",
    \"assetId\": \"assetId\",
    \"protocol\": \"dataspace-protocol-http\",
    \"transferType\":\"HttpData-PULL\",
    \"dataDestination\": {
      \"type\": \"HttpProxy\"
    }
  }" \
  -s | jq`` can anyone help me? Thanks to all