version: "2.3"
services:
  # Conector
  company1:
    container_name: provider # Nombre del contenedor
    build:
      context: ./ # Donde se encuentra la raíz
    environment: 
      EDC_CONNECTOR_NAME: provider # Nombre del conector
      EDC_VAULT: /configuracion/conf/vault.properties # Ruta hasta el vault, es donde está el certificado
      EDC_FS_CONFIG: /configuracion/conf/configuration.properties # Ruta hasta las propiedades de configuración
      EDC_IAM_DID_WEB_USE_HTTPS: "true" # Forzar el uso de https
     # Puertos, la "explicación" de cada uno se encuentra en sus propiedades especificas
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
    volumes:
      - ./configuracion:/configuracion # Volumen añadido al contenedor de docker, para tener acceso a toda la configuración

  company2:
    container_name: consumer # Nombre del contenedor
    build: 
      context: ./ # Donde se encuentra la raíz
    environment: 
      EDC_CONNECTOR_NAME: consumer # Nombre del conector
      EDC_VAULT: /configuracion/conf2/vault.properties # Ruta hasta el vault, es donde está el certificado
      EDC_FS_CONFIG: /configuracion/conf2/configuration.properties # Ruta hasta las propiedades de configuración
      EDC_IAM_DID_WEB_USE_HTTPS: "true" # Forzar el uso de https

     # Puertos, la "explicación" de cada uno se encuentra en sus propiedades especificas
    ports:
      - "29191:29191"       
      - "29193:29193"       
      - "29194:29194"       
      - "29291:29291"       
      - "29192:29192"       
    volumes:
      - ./configuracion:/configuracion # Volumen añadido al contenedor de docker, para tener acceso a toda la configuración

  # Base de datos
  postgres1:
    container_name: postgres1 # Nombre del contenedor de postgres
    image: postgres:13.4 # Imagen y version a utilizar
    ports:
      - "5432:5432" # Puerto para acceder desde la maquina anfitiron
    environment:
      POSTGRES_USER: postgres # Usuario para conectarse
      POSTGRES_PASSWORD: edcpassword # Contraseña para conectarse
    volumes:
      - ./configuracion/db:/docker-entrypoint-initdb.d/ # Ruta hasta la carpeta que contiene el script «init.sql»

  postgres2:
    container_name: postgres2 # Nombre del contenedor de postgres
    image: postgres:13.4 # Imagen y version a utilizar
    ports:
      - "5433:5432" # Puerto para acceder desde la maquina anfitiron
    environment:
      POSTGRES_USER: postgres # Usuario para conectarse
      POSTGRES_PASSWORD: edcpassword # Contraseña para conectarse
    volumes:
      - ./configuracion/db:/docker-entrypoint-initdb.d/ # Ruta hasta la carpeta que contiene el script «init.sql»

  logger:
    build:
      context: ../http-request-logger
    ports:
      - "4000:4000"

  hashicorp-vault:
    container_name: vault-server
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"