#!/bin/bash

curl -d "{  \"@context\": {    \"@vocab\": \"https://w3id.org/edc/v0.0.1/ns/\"  },
  \"@type\": \"ContractRequest\",
  \"counterPartyAddress\": \"https://sergio.arlabdevelopments.com:19194/protocol\",
  \"protocol\": \"dataspace-protocol-http\",
  \"policy\": {    \"@context\": \"http://www.w3.org/ns/odrl.jsonld\",
    \"@id\": \"$1\",
    \"@type\": \"Offer\",
    \"assigner\": \"provider\",
    \"target\": \"assetId\"  }}" \
  -X POST -H 'content-type: application/json' https://sergio.arlabdevelopments.com:29193/management/v2/contractnegotiations \
  --header 'x-api-key: password' \
-s | jq '."@id"'  | tr -d \" 