#!/bin/bash

curl -X POST "http://localhost:29193/management/v2/transferprocesses" \
  -H "Content-Type: application/json" \
  -d "{  \"@context\": {    \"@vocab\": \"https://w3id.org/edc/v0.0.1/ns/\"  },  \"@type\": \"TransferRequestDto\",  \"connectorId\": \"provider\",  \"counterPartyAddress\": \"http://provider:19194/protocol\",  \"contractId\": \"$1\",  \"assetId\": \"assetId\",  \"protocol\": \"dataspace-protocol-http\",  \"dataDestination\": {    \"type\": \"HttpData\",    \"baseUrl\": \"http://consumer:29191/api/endpoint\"  }}" \
-s | jq