#!/bin/bash

vault login hvs.4tfgCA7Zu0YIlL3v7GP9AX0L

private_key=$(cat $1)
certificate=$(cat $2)

vault kv put secret/private_key content="$private_key"
vault kv put secret/certificate content="$certificate"
vault kv put secret/api_key content="password"