#!/bin/bash

export VAULT_ADDR="http://0.0.0.0:8200";

vault login token

private_key=$(cat $1)
certificate=$(cat $2)

vault kv put secret/private_key content="$private_key"
vault kv put secret/certificate content="$certificate"