version: "2.3"
services:
  # Conector
  company1:
    container_name: provider # Nombre del contenedor
    build:
      context: ../connecor # Donde se encuentra la raíz
    environment: 
      EDC_FS_CONFIG: /configuracion/conf/configuration.properties # Ruta hasta las propiedades de configuración
      EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: https://sergio.arlabdevelopments.com:19192/control/token
    # Puertos, la "explicación" de cada uno se encuentra en sus propiedades especificas
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
    volumes:
      - ./configuracion:/configuracion # Volumen añadido al contenedor de docker, para tener acceso a toda la configuración

  company2:
    container_name: consumer # Nombre del contenedor
    build: 
      context: ../connecor # Donde se encuentra la raíz
    environment: 
      EDC_FS_CONFIG: /configuracion/conf2/configuration.properties # Ruta hasta las propiedades de configuración

    # Puertos, la "explicación" de cada uno se encuentra en sus propiedades especificas
    ports:
      - "29191:29191"
      - "29193:29193"
      - "29194:29194"
      - "29291:29291"
      - "29192:29192"
    volumes:
      - ./configuracion:/configuracion # Volumen añadido al contenedor de docker, para tener acceso a toda la configuración

  # Base de datos
  postgres1:
    container_name: postgres1 # Nombre del contenedor de postgres
    image: postgres:13.4 # Imagen y version a utilizar
    ports:
      - "5432:5432" # Puerto para acceder desde la maquina anfitiron
    environment:
      POSTGRES_USER: postgres # Usuario para conectarse
      POSTGRES_PASSWORD: edcpassword # Contraseña para conectarse
    volumes:
      - ./configuracion/db:/docker-entrypoint-initdb.d/ # Ruta hasta la carpeta que contiene el script «init.sql»
    depends_on:
      - company1

  postgres2:
    container_name: postgres2 # Nombre del contenedor de postgres
    image: postgres:13.4 # Imagen y version a utilizar
    ports:
      - "5433:5432" # Puerto para acceder desde la maquina anfitiron
    environment:
      POSTGRES_USER: postgres # Usuario para conectarse
      POSTGRES_PASSWORD: edcpassword # Contraseña para conectarse
    volumes:
      - ./configuracion/db:/docker-entrypoint-initdb.d/ # Ruta hasta la carpeta que contiene el script «init.sql»
    depends_on:
      - company2

  # Vault para almacenar los certificados
  hashicorp-vault:
    container_name: vault-server 
    image: vault:1.13.3 # Imagen del vaul que vamos a utilizar
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: token # Token raíz para conectarnos al vaul
      VAULT_ROOT_TOKEN_ID: token # Token raíz para conectarnos al vaul
      VIRTUAL_HOST: vault-server.com
      VAULT_SKIP_VERIFY: true
    ports:
      - "8200:8200" # Puerto tanto de la interfaz gráfica como del API
    volumes:
      - ./configuracion:/configuracion
    entrypoint: vault server -config=/configuracion/vault/vault.hcl 


       